# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rufus-scheduler}
  s.version = "2.0.7"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["John Mettraux"]
  s.date = %q{2010-11-09}
  s.description = %q{
    job scheduler for Ruby (at, cron, in and every jobs).

    By default uses a Ruby thread, if EventMachine is present, it will rely on it.
  }
  s.email = %q{jmettraux@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
     "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     ".rspec",
     "CHANGELOG.txt",
     "CREDITS.txt",
     "LICENSE.txt",
     "README.rdoc",
     "Rakefile",
     "TODO.txt",
     "lib/rufus-scheduler.rb",
     "lib/rufus/otime.rb",
     "lib/rufus/sc/cronline.rb",
     "lib/rufus/sc/jobqueues.rb",
     "lib/rufus/sc/jobs.rb",
     "lib/rufus/sc/rtime.rb",
     "lib/rufus/sc/scheduler.rb",
     "lib/rufus/sc/version.rb",
     "lib/rufus/scheduler.rb",
     "misc/cronline_next_time_cost.rb",
     "rufus-scheduler.gemspec",
     "spec/at_in_spec.rb",
     "spec/at_spec.rb",
     "spec/blocking_spec.rb",
     "spec/cron_spec.rb",
     "spec/cronline_spec.rb",
     "spec/every_spec.rb",
     "spec/exception_spec.rb",
     "spec/in_spec.rb",
     "spec/rtime_spec.rb",
     "spec/schedulable_spec.rb",
     "spec/scheduler_spec.rb",
     "spec/spec_base.rb",
     "spec/stress_schedule_unschedule_spec.rb",
     "spec/timeout_spec.rb",
     "test/kjw.rb",
     "test/t.rb"
  ]
  s.homepage = %q{http://github.com/jmettraux/rufus-scheduler/}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{rufus}
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{job scheduler for Ruby (at, cron, in and every jobs)}
  s.test_files = [
    "spec/at_in_spec.rb",
     "spec/at_spec.rb",
     "spec/blocking_spec.rb",
     "spec/cron_spec.rb",
     "spec/cronline_spec.rb",
     "spec/every_spec.rb",
     "spec/exception_spec.rb",
     "spec/in_spec.rb",
     "spec/rtime_spec.rb",
     "spec/schedulable_spec.rb",
     "spec/scheduler_spec.rb",
     "spec/spec_base.rb",
     "spec/stress_schedule_unschedule_spec.rb",
     "spec/timeout_spec.rb",
     "test/kjw.rb",
     "test/t.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<tzinfo>, [">= 0"])
      s.add_development_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<tzinfo>, [">= 0"])
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<rspec>, ["~> 2.0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<tzinfo>, [">= 0"])
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<rspec>, ["~> 2.0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

